Repository chintan9/plyr-react, pull requests merged in 2020-10, with the labels that each got.

#340 add all-contributors
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: size/M, 🔍 Ready for Review

#354 Compare PR
  .all-contributorsrc
  .github/workflows/npm-publish.yml
  README.md
  package-lock.json
  package.json
Labels: size/M, 🔍 Ready for Review

#355 Replace memo with forwardRef
  README.md
  package-lock.json
  package.json
  src/Plyr.tsx
  test/Plyr.test.tsx
Labels: size/M, ✅ Approved

#371 Create Build.yml
  sonar-project.properties
Labels: size/S, 🔍 Ready for Review

#370 Fix forward ref again
  README.md
  package-lock.json
  package.json
  rollup.config.js
  src/Plyr.example.md
  src/index.ts
  src/index.tsx
  src/plyr-react.d.ts
  test/Plyr.test.tsx
  tsconfig.json
Labels: ✅ Approved

#372 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: size/XS, 🔍 Ready for Review

#373 Add changelog
  .remarkignore
  CHANGELOG.md
Labels: size/L, 🔍 Ready for Review

#374 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: size/XS, 🔍 Ready for Review

#375 Update package.json
  package.json
Labels: size/XS, 🔍 Ready for Review

#380 Fix/plyr crash
  package-lock.json
  src/index.tsx
  test/Plyr.test.tsx
Labels: ✅ Approved

#393 Create starrycake.yml
  .github/starrycake.yml
Labels: question, size/L, 🔍 Ready for Review

#392 Update docs
  README.md
  test/Plyr.test.tsx
Labels: documentation, size/S, 🔍 Ready for Review

#396 clean up readme
  README.md
Labels: size/S, 🔍 Ready for Review
