Repository chintan9/plyr-react, pull requests merged in 2020-07, with the labels that each got.

#260 Try to move TS by iwatakeshi #258
  .editorconfig
  .prettierrc
  package-lock.json
  package.json
  rollup.config.js
  src/index.d.ts
  src/index.ts
  src/lib/components/PlyrComponent/PlyrComponent.js
  src/lib/components/PlyrComponent/PlyrComponent.test.js
  src/lib/components/PlyrComponent/index.js
  src/lib/index.js
  src/plyr.d.ts
  src/plyr/PlyComponent.examples.md
  src/plyr/PlyrComponent.d.ts
  src/plyr/PlyrComponent.test.d.ts
  src/plyr/PlyrComponent.test.tsx
  src/plyr/PlyrComponent.tsx
  src/plyr/styles.css
  tsconfig.json
  yarn.lock
Labels: 🔍 Ready for Review

#263 V3 ts
  .github/workflows/nodejs.yml
  .prettierrc
  .typo-ci.yml
  package-lock.json
  package.json
  src/plyr.d.ts
  src/plyr/PlyComponent.examples.md
  src/plyr/PlyrComponent.d.ts
  src/plyr/PlyrComponent.test.tsx
  src/plyr/PlyrComponent.tsx
  tsconfig.json
Labels: 🔍 Ready for Review

#262 [PR] Convert project to TypeScript
  .eslintrc.json
  .typo-ci.yml
  README.md
  config/webpack.js
  package.json
  rollup.config.js
  src/Plyr.example.md
  src/Plyr.tsx
  src/index.d.ts
  src/index.ts
  src/plyr.d.ts
  src/plyr/PlyComponent.examples.md
  src/plyr/PlyrComponent.d.ts
  src/plyr/PlyrComponent.test.d.ts
  src/plyr/PlyrComponent.tsx
  src/plyr/styles.css
  test/Plyr.test.tsx
  tsconfig.json
Labels: size/XL, ✅ Approved

#264 V3 master to v3-ts
  .docz/.eslintrc.json
  .docz/app/db.json
  .docz/gatsby-node.js
  .docz/public/404.html
  .docz/public/404/index.html
  .docz/public/798c9f31-fb961b3b8ef528ff32f9.js
  .docz/public/798c9f31-fb961b3b8ef528ff32f9.js.map
  .docz/public/app-b34ea0c9e35cc7ce783f.js
  .docz/public/app-b34ea0c9e35cc7ce783f.js.map
  .docz/public/chunk-map.json
  .docz/public/code-of-conduct/index.html
  .docz/public/component---code-of-conduct-md-493e7d040274b9a964ca.js
  .docz/public/component---code-of-conduct-md-493e7d040274b9a964ca.js.map
  .docz/public/component---contributing-md-0aa02061278c2bb2e1b0.js
  .docz/public/component---contributing-md-0aa02061278c2bb2e1b0.js.map
  .docz/public/component---readme-md-c2a320a7b9585447b765.js
  .docz/public/component---readme-md-c2a320a7b9585447b765.js.map
  .docz/public/component---security-md-65c895b5a1cdc9375532.js
  .docz/public/component---security-md-65c895b5a1cdc9375532.js.map
  .docz/public/component---src-index-mdx-aa52803fd5b232b75aa5.js
  .docz/public/component---src-index-mdx-aa52803fd5b232b75aa5.js.map
  .docz/public/component---src-pages-404-js-e24f59d6d34854cdc89c.js
  .docz/public/component---src-pages-404-js-e24f59d6d34854cdc89c.js.map
  .docz/public/component---src-plyr-example-md-ee9f8b964a753e0ae850.js
  .docz/public/component---src-plyr-example-md-ee9f8b964a753e0ae850.js.map
  .docz/public/contributing/index.html
  .docz/public/e7e9ea0489a130ff82a98eb7e53ca79fba855964-7a0cadd276d9e07a1883.js
  .docz/public/e7e9ea0489a130ff82a98eb7e53ca79fba855964-7a0cadd276d9e07a1883.js.map
  .docz/public/framework-d9ab37605d07b4745a8b.js
  .docz/public/framework-d9ab37605d07b4745a8b.js.map
  .docz/public/index.html
  .docz/public/page-data/app-data.json
  .docz/public/page-data/dev-404-page/page-data.json
  .docz/public/page-data/index/page-data.json
  .docz/public/page-data/readme/page-data.json
  .docz/public/page-data/src-plyr-example/page-data.json
  .docz/public/page-data/src-plyr-plyr-component-examples/page-data.json
  .docz/public/polyfill-4a3b683902c8b5560e8b.js
  .docz/public/polyfill-4a3b683902c8b5560e8b.js.map
  .docz/public/readme/index.html
  .docz/public/security/index.html
  .docz/public/src-plyr-example/index.html
  .docz/public/static/d/1635659820.json
  .docz/public/styles-5379f07abcd59a0e64bf.js
  .docz/public/styles-5379f07abcd59a0e64bf.js.map
  .docz/public/styles.2543ff947a193d7f33b1.css
  .docz/public/webpack-runtime-2e6053cd4fed63f1cfde.js
  .docz/public/webpack-runtime-2e6053cd4fed63f1cfde.js.map
  .docz/public/webpack.stats.json
  .github/workflows/nodejs.yml
  .gitignore
  .typo-ci.yml
  package-lock.json
  package.json
  src/index.mdx
Labels: ⚠️ Changes requested
